apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-postgres
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: azure-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: azure-postgres
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: madera
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: madera
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: madera
        image: maderaacr.azurecr.io/kells64000projetmaderacesi_azure-madera:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: postgres
          value: "azure-postgres"
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: madera
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: madera