version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    container_name: azure-postgres
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
  azure-madera:
    build: .
    command: python3 /var/www/html/madera/manage.py runserver 0.0.0.0:8000
    container_name: azure-madera
    volumes:
      - .:/var/www/html/madera
    environment:
      POSTGRES: azure-postgres
    ports:
      - 80:8000
    tty: true
#    depends_on:
#      - db

#volumes:
#  postgres_data: