# Generated by Django 2.1.5 on 2019-03-03 16:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190302_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Pays'),
        ),
    ]
