# Generated by Django 2.1.5 on 2019-02-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('nature', models.CharField(max_length=20, verbose_name='nature')),
                ('length', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='width')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='depth')),
                ('unit', models.CharField(max_length=10, verbose_name='unit')),
                ('designer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
