# Generated by Django 2.1.5 on 2019-03-05 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0003_auto_20190227_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
            ],
            bases=('components.component',),
        ),
        migrations.RemoveField(
            model_name='component',
            name='designer',
        ),
        migrations.AddField(
            model_name='module',
            name='components',
            field=models.ManyToManyField(related_name='material', to='components.Component'),
        ),
        migrations.AddField(
            model_name='module',
            name='designer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamme',
            name='components',
            field=models.ManyToManyField(related_name='finishing', to='components.Component'),
        ),
    ]
