# Generated by Django 2.1.5 on 2019-03-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20190305_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('SQR', 'square'), ('REC', 'rectangle'), ('CUS', 'custom')], max_length=3, verbose_name='shape')),
                ('shape_img', models.FileField(null=True, upload_to='', verbose_name='shape_img')),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='family',
        ),
        migrations.RemoveField(
            model_name='gamme',
            name='module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='component',
        ),
        migrations.AddField(
            model_name='gamme',
            name='modules',
            field=models.ManyToManyField(to='components.Module'),
        ),
        migrations.AddField(
            model_name='gamme',
            name='ratio',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='module',
            name='components',
            field=models.ManyToManyField(to='components.Component'),
        ),
        migrations.AddField(
            model_name='module',
            name='family',
            field=models.CharField(choices=[('EX', 'exterior'), ('IN', 'insulator'), ('CV', 'cover')], max_length=3, null=True, verbose_name='family'),
        ),
        migrations.AlterField(
            model_name='component',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit',
            field=models.CharField(max_length=10, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='component',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='module',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='module',
            name='unit',
            field=models.CharField(max_length=10, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='module',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='width'),
        ),
        migrations.AddField(
            model_name='house',
            name='modules',
            field=models.ManyToManyField(to='components.Module'),
        ),
    ]
