# Generated by Django 2.1.5 on 2019-03-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20190311_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='module',
            name='depth',
        ),
        migrations.AddField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
