# Generated by Django 2.1.5 on 2019-03-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20190311_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='depth'),
        ),
        migrations.AddField(
            model_name='module',
            name='angle_type',
            field=models.CharField(max_length=20, null=True, verbose_name='angle_type'),
        ),
    ]
