# Generated by Django 2.1.5 on 2019-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20190311_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='width',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='gamme',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='gamme',
            name='quality',
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.CharField(max_length=30, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='component',
            name='gammes',
            field=models.ManyToManyField(to='components.Gamme'),
        ),
        migrations.AddField(
            model_name='house',
            name='gamme',
            field=models.ManyToManyField(to='components.Gamme'),
        ),
        migrations.AddField(
            model_name='module',
            name='gammes',
            field=models.ManyToManyField(to='components.Gamme'),
        ),
        migrations.AddField(
            model_name='module',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
    ]
