# Generated by Django 2.1.5 on 2019-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20190311_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='gamme',
            name='name',
            field=models.CharField(choices=[('EXL', 'excellence'), ('LUX', 'luxe'), ('NAT', 'natural')], max_length=30, verbose_name='name'),
        ),
    ]
