# Generated by Django 2.1.5 on 2019-03-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20190311_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='nature',
            field=models.CharField(choices=[('SYN', 'synthetic'), ('NAT', 'natural'), ('BIO', 'biological')], max_length=3, null=True, verbose_name='nature'),
        ),
    ]
