# Generated by Django 2.1.5 on 2019-03-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20190311_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='price',
        ),
    ]
