# Generated by Django 2.1.5 on 2019-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_remove_module_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='nature',
            field=models.CharField(max_length=20, null=True, verbose_name='nature'),
        ),
        migrations.AlterField(
            model_name='gamme',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='house',
            name='shape',
            field=models.CharField(max_length=20, verbose_name='shape'),
        ),
        migrations.AlterField(
            model_name='module',
            name='family',
            field=models.CharField(max_length=3, null=True, verbose_name='family'),
        ),
    ]
