# Generated by Django 2.1.5 on 2019-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_auto_20190311_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='shape_img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='house',
            name='shape',
        ),
        migrations.AlterField(
            model_name='module',
            name='family',
            field=models.CharField(choices=[('EXT', 'exterieur'), ('INT', 'interieur'), ('TOI', 'toiture'), ('DAL', 'sol_dalle'), ('PLA', 'sol_plancher'), ('CHA', 'charpente')], max_length=3, null=True, verbose_name='family'),
        ),
        migrations.AlterField(
            model_name='module',
            name='nature',
            field=models.CharField(max_length=20, null=True, verbose_name='nature'),
        ),
    ]
