# Generated by Django 2.1.5 on 2019-01-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maderauser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
