# Generated by Django 2.1.5 on 2019-01-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190127_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='maderauser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
    ]
