# Generated by Django 2.1.5 on 2019-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_maderauser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maderauser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='maderauser',
            name='username',
            field=models.CharField(default='unknown', max_length=50, verbose_name='username'),
        ),
    ]
