# Generated by Django 2.1.5 on 2019-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_maderauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='maderauser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='assets/users-media/avatars/'),
        ),
    ]
