# Generated by Django 2.1.5 on 2019-02-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0006_maderauser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maderauser',
            name='location',
        ),
        migrations.AddField(
            model_name='maderauser',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='addresses.Address'),
        ),
    ]
