# Generated by Django 2.1.5 on 2019-02-11 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190211_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maderauser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
