# Generated by Django 2.1.5 on 2019-02-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190211_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maderauser',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='addresses.Address'),
        ),
    ]
