# Generated by Django 2.1.5 on 2019-03-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_maderauser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maderauser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='phone'),
        ),
    ]
