# Generated by Django 2.1.5 on 2019-03-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190306_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maderauser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='phone'),
        ),
    ]
