# Generated by Django 2.1.5 on 2019-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190306_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maderauser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
