# Generated by Django 2.1.5 on 2019-03-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190312_1448'),
        ('users', '0017_auto_20190331_2306'),
    ]

    operations = [
    ]
