# Generated by Django 2.1.5 on 2019-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_name', models.CharField(max_length=30)),
                ('quote_phone', models.CharField(max_length=10)),
                ('quote_email', models.EmailField(max_length=254)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_date', models.DateField()),
                ('quote_state', models.TextField()),
            ],
        ),
    ]
