# Generated by Django 2.1.5 on 2019-02-03 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_date',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
