# Generated by Django 2.1.5 on 2019-02-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190203_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_updated_at',
            new_name='updated_at',
        ),
    ]
