# Generated by Django 2.1.5 on 2019-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190203_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.TextField(default='null'),
        ),
    ]
