# Generated by Django 2.1.5 on 2019-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attachment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
