# Generated by Django 2.1.5 on 2019-02-27 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0005_auto_20190217_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone',
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='salesman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
