# Generated by Django 2.1.5 on 2019-02-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190211_1449'),
        ('quotes', '0006_auto_20190227_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='salesman',
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='users.Client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='salesperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesperson', to='users.SalesPerson'),
        ),
    ]
