# Generated by Django 2.1.5 on 2019-03-05 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20190227_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
