# Generated by Django 2.1.5 on 2019-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20190306_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reference',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
