# Generated by Django 2.1.5 on 2019-03-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20190309_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='attachment'),
        ),
    ]
