# Generated by Django 2.1.5 on 2019-03-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quote_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/pdf/', verbose_name='attachment'),
        ),
    ]
