# Generated by Django 2.1.5 on 2019-06-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_merge_20190331_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
